### ISSUE TITLE
[Foundation] Initial Project Setup

### ISSUE THREAD

**Issue by 75py** [75py/habit-tracker#1]
```yml
Description: "Build the foundational structure for the project. This includes adding dependencies, creating the package structure for a layered architecture, and setting up the DI container."
Tasks:
  - |
    Add the following libraries to `gradle/libs.versions.toml` and set up the dependencies in `build.gradle.kts`.
      - Room for KMP (`androidx.room:room-runtime`, `androidx.room:room-compiler`)
      - Koin for KMP (`io.insert-koin:koin-core`, `io.insert-koin:koin-compose`, `io.insert-koin:koin-android`)
      - kotlinx.datetime
  - |
    Create the following package structure under `shared/src/commonMain/kotlin`.
      - com.nagopy.kmp.habittracker.data (Data Layer)
      - com.nagopy.kmp.habittracker.domain (Domain Layer)
      - com.nagopy.kmp.habittracker.presentation (Presentation Layer)
  - "Set up the initial Koin configuration. Add code to initialize the DI container at the entry points of each platform (androidApp, iosApp)."
Documentation:
  - |
    Create `README.md` and describe the following:
      - Project overview
      - Key technologies used (KMP, Compose Multiplatform, Room, Koin)
  - |
    Create `docs/ARCHITECTURE.md` and describe the following:
      - An overview of the layered architecture to be adopted (UI - Domain - Data)
      - A basic explanation of the responsibilities of each layer
Acceptance Criteria:
  - "The project builds successfully, and the package structure and initial DI setup are complete."
  - "Basic README.md and ARCHITECTURE.md files have been created."
```
