### ISSUE TITLE
[Refactor] Support for Habits Repeating Multiple Times a Day

### ISSUE THREAD

**Issue by 75py** [75py/habit-tracker#11]
```yaml
Description: |
  The current implementation assumes a habit is completed once per day. This task refactors the existing domain and presentation layers to correctly handle habits that need to be performed multiple times a day (e.g., "Drink water every hour").
Tasks:
  - |
    **1. Refactor Domain Layer:**
      - Define or modify the `Task.kt` domain model (a specific instance of a habit with a scheduled time and a completion status) in the `domain/model` package.
      - Refactor `GetTodayTasksUseCase` to dynamically generate a list of all `Task` instances for the current day based on each `Habit`'s schedule.
      - Refactor `CompleteTaskUseCase` to mark a specific `Task` instance (identified by habit ID and its scheduled time) as complete.
  - |
    **2. Refactor Presentation Layer (UI):**
      - Refactor `TodayViewModel` to receive and expose the list of `Task` instances from the UseCase.
      - Refactor `TodayScreen.kt` to display a list of time-based task instances (e.g., "10:00 Drink Water," "11:00 Drink Water"). Each instance must be individually checkable.
Testing:
  - "Modify and add unit tests for the updated UseCases and ViewModels to match the new logic."
  - "Update the UI tests for `TodayScreen` to reflect the new specification."
Documentation:
  - "Update `ARCHITECTURE.md` and `SPECIFICATIONS.md` to reflect this refactoring. Clearly document the distinction between a `Habit` (the rule) and a `Task` (the instance)."
Acceptance Criteria:
  - "A habit set to repeat hourly is displayed on the 'Today' screen as a list of individual, time-stamped tasks."
  - "Each task instance can be marked as complete independently."
  - "All related tests are passing."
```
