### ISSUE TITLE
[Feature] Implement Notification Feature

### ISSUE THREAD

**Issue by 75py** [75py/habit-tracker#13]
```yaml
Description: "Implement a feature to send notifications to the user at scheduled times and allow them to perform actions directly from the notification."
Tasks:
  - "Define a `NotificationScheduler` interface in the `domain` layer for scheduling notifications."
  - "Implement the `NotificationScheduler` interface in `androidApp` and `iosApp` using platform-specific APIs. Ensure it schedules notifications based on the scheduled times of the refactored `Task` instances."
  - "Add a 'Complete' action button to the notification and implement the logic to execute the `CompleteTaskUseCase` in the background when it's tapped."
Documentation:
  - |
    Add a "Notification Feature" section to `docs/ARCHITECTURE.md` and describe:
      - The design of separating a shared interface from platform-specific implementations.
      - The processing flow for interactive notifications.
Acceptance Criteria:
  - "Notifications are delivered at the scheduled times, and tasks can be completed via the notification button."
  - "Related documentation has been updated."
```
