### ISSUE TITLE
[Chore] Setup Logging with Napier

### ISSUE THREAD

**Issue by 75py** [75py/habit-tracker#17]
```yaml
Description: "Integrate the Napier logging library to establish a consistent logging strategy throughout the project for easier debugging and error tracking."
Tasks:
    - "Add the Napier dependency (`io.github.aakira:napier:2.7.1`) to `gradle/libs.versions.toml` and the appropriate `build.gradle.kts` files."
    - "Initialize Napier in the application entry points for both Android and iOS. Use `DebugAntilog` to ensure logs are only printed in debug builds."
    - "Add a rule to the project's coding standards: All new code must use `Napier.d()` for debug information and `Napier.e(it)` inside any `catch` block to log exceptions."
Documentation:
    - "Update `README.md` to list Napier as a key dependency."
    - "Briefly mention the logging strategy (e.g., 'Log all caught exceptions') in `docs/ARCHITECTURE.md`."
Acceptance Criteria:
    - "The Napier dependency is successfully added, and the project builds."
    - "Debug logs sent from the app are visible in Logcat (Android) and the Xcode console (iOS)."
    - "The project's coding standards for logging are documented."
```
