### ISSUE TITLE
[Bug] Unify Notification Permission Request on App Launch

### ISSUE THREAD

**Issue by 75py** [75py/habit-tracker#19]
```yaml
Description: |
  The notification permission dialog is handled inconsistently. On Android, it doesn't appear at all. On iOS, it appears only on the first view of the 'Today's Tasks' screen. The request should be standardized to occur on the first app launch for both platforms.
Tasks:
  - "Implement a unified permission request logic within the shared module, if possible, or define a common trigger point."
  - "Ensure this logic is called at application startup on both Android and iOS."
Acceptance Criteria:
  - "On the first launch, both iOS and Android versions of the app prompt the user for notification permissions."
```
