### ISSUE TITLE
[Feature] Enable Editing and Deleting from HabitListScreen

### ISSUE THREAD

**Issue by 75py** [75py/habit-tracker#20]
```yaml
Description: "Currently, tapping an item on the `HabitListScreen` has no effect. Users should be able to edit or delete existing habits directly from this list to improve usability."
Tasks:
  - "Implement a context menu, long-press gesture, or visible buttons on each list item to trigger 'Edit' and 'Delete' actions."
  - "Tapping 'Edit' should navigate to the `HabitEditScreen`, pre-filled with the selected habit's data."
  - "Tapping 'Delete' should show a confirmation dialog before permanently removing the habit."
Acceptance Criteria:
  - "Users can successfully open the edit screen for an existing habit from the list."
  - "Users can successfully delete a habit from the list after confirming the action."
```
