### ISSUE TITLE
[UI] Improve Visibility of Selected Color in HabitEditScreen

### ISSUE THREAD

**Issue by 75py** [75py/habit-tracker#21]
```yaml
Description: "It is difficult for users to determine which color is currently selected in the color picker on the `HabitEditScreen`. The visual feedback for the selected state needs to be enhanced."
Tasks:
  - "Modify the color picker Composable to add a prominent border, checkmark, or other clear visual indicator to the currently selected color item."
Acceptance Criteria:
  - "The currently selected color is clearly and unambiguously indicated to the user."
```
