### ISSUE TITLE
[Bug] 'Hourly' Frequency Should Lock Interval to 1 Hour

### ISSUE THREAD

**Issue by 75py** [75py/habit-tracker#22]
```yaml
Description: |
  When a user selects the 'Hourly' frequency for a habit, the UI still allows them to set a custom 'Every xx hours' interval. This is contradictory. If 'Hourly' is chosen, the interval should be non-editable and fixed at 1 hour.
Tasks:
  - "In the `HabitEditViewModel`, add logic to disable the interval input field when the selected frequency is 'Hourly'."
  - "Automatically set the interval value to 1 when 'Hourly' is selected."
Acceptance Criteria:
  - "When the 'Hourly' frequency is selected, the interval setting is disabled in the UI and its value is fixed at 1."
```
