### ISSUE TITLE
[Feature] Allow Minute-Based Intervals for Habits

### ISSUE THREAD

**Issue by 75py** [75py/habit-tracker#23]
```yaml
Description: "The current interval selection is limited to hours. To support more granular habits (e.g., 'stretch every 30 minutes'), the app should allow users to set intervals in minutes as well."
Tasks:
  - "Update the `Habit` data model and database schema to store intervals in minutes instead of hours."
  - "Modify the `HabitEditScreen` UI to allow users to input a number and select a unit (e.g., minutes, hours)."
  - "Update the domain logic to correctly calculate task instances based on minute-based intervals."
Acceptance Criteria:
  - "Users can create and save a habit that repeats at an interval defined in minutes."
  - "The scheduling logic correctly creates tasks based on the minute-based interval."
Notes:
  - "Since this time it has not been released yet, the database migration process is not necessary since the data will be deleted and redone once."
```
