### ISSUE TITLE
[Refactor] Use Material3 TimePicker in HabitEditScreen

### ISSUE THREAD

**Issue by 75py** [75py/habit-tracker#24]
```yaml
Description: "The start time selection on the `HabitEditScreen` should be updated to use the standard `androidx.compose.material3.TimePicker` from Compose Multiplatform Material 3 for a better and more consistent user experience."
Tasks:
  - "Replace the current time input method with a dialog containing the M3 `TimePicker` Composable."
Acceptance Criteria:
  - "Selecting the start time on the `HabitEditScreen` opens the standard Material 3 TimePicker dialog."
```
