### ISSUE TITLE
[Bug] Navigation Fails After Saving in HabitEditScreen

### ISSUE THREAD

**Issue by 75py** [75py/habit-tracker#25]
```yaml
Description: |
  After tapping the 'Save' button in the `HabitEditScreen`, a loading indicator is shown, but the screen gets stuck and never navigates back. The data is saved correctly (visible after a restart), suggesting the issue is with navigation or state handling after a successful save.
Tasks:
  - "Investigate the ViewModel and Screen logic for any code paths that could be causing a deadlock or preventing the navigation event."
  - "Ensure state updates from the save operation are correctly observed on the main thread to trigger navigation."
Acceptance Criteria:
  - "After saving a habit, the loading indicator disappears, and the app correctly navigates back to the previous screen."
```
