### ISSUE TITLE
[Bug] Checkbox on TodayScreen is Unresponsive

### ISSUE THREAD

**Issue by 75py** [75py/habit-tracker#26]
```yaml
Description: "On the `TodayScreen`, tapping a task's checkbox does not change its state. The view seems to redraw momentarily, but the checkmark does not turn on or off. This occurs on both iOS and Android, suggesting an issue in the shared code."
Tasks:
  - "Debug the `onCheckedChange` lambda for the `Checkbox` Composable on the `TodayScreen`."
  - "Verify the `TodayViewModel` is receiving the event and calling the `CompleteTaskUseCase`."
  - "Ensure the UI state (`StateFlow` or similar) is being updated correctly after the UseCase completes to trigger a recomposition with the new state."
Acceptance Criteria:
  - "Tapping a checkbox on the `TodayScreen` correctly toggles its state, and the change persists."
```
