### ISSUE TITLE
[Bug] Incorrect Content in Push Notifications

### ISSUE THREAD

**Issue by 75py** [75py/habit-tracker#27]
```yaml
Description: "The push notifications on iOS are not displaying the correct content. They should use the title and description from the `Habit` they correspond to."
Tasks:
  - "In the iOS-specific `NotificationScheduler` implementation, ensure the habit's title and description are correctly extracted from the payload."
  - "Use these values to construct the `UNMutableNotificationContent` for the notification."
  - "Check Android implementations for similar issues."
Acceptance Criteria:
  - "Notifications on iOS correctly display the title and a relevant body text from the corresponding habit."
```
