### ISSUE TITLE
[Bug] [Android] Push Notifications Are Not Being Delivered

### ISSUE THREAD

**Issue by 75py** [75py/habit-tracker#28]
```yaml
Description: "Push notifications are not arriving on Android devices. This could be an issue with the `AlarmManager`, `BroadcastReceiver`, notification channel setup, or permissions."
Tasks:
  - "Verify the notification permission is correctly requested and its status is checked before scheduling."
  - "Debug the `AlarmManager` scheduling logic to ensure alarms are being set correctly."
  - "Use logging or the debugger to verify that the `BroadcastReceiver`'s `onReceive` method is being triggered at the correct time."
  - "Confirm that the Notification Channel is created correctly before attempting to display a notification."
Acceptance Criteria:
  - "Scheduled notifications are successfully delivered to the user on Android devices."
```
