### ISSUE TITLE
[Data] Implement Data Layer with Room

### ISSUE THREAD

**Issue by 75py** [75py/habit-tracker#3]
```yaml
Description: "Implement the data layer for persistence using Room for KMP to store habits and completion logs."
Tasks:
  - "Define Entities in the `data/local` package: `HabitEntity.kt` and `LogEntity.kt`."
  - "Define `HabitDao.kt` in the `data/local` package."
  - "Define `AppDatabase.kt` (RoomDatabase) in the `data/local` package."
  - "Create `HabitRepositoryImpl.kt` in the `data` package to implement the domain layer's interface using `HabitDao`."
Testing:
  - "Write unit tests using `androidx.room:room-testing` to verify that each query in `HabitDao` works correctly."
Documentation:
  - |
    Update the "Data Layer" section in `docs/ARCHITECTURE.md` to include:
      - The roles of Room's Entity, DAO, and Database
      - How `RepositoryImpl` uses the DAO
Acceptance Criteria:
  - "The definitions and implementations of Entity, DAO, and Database are complete."
  - "Unit tests for the DAO are passing."
  - "Related documentation has been updated."
```
