### ISSUE TITLE
[Feature] Add End Time for Interval-Based Habits

### ISSUE THREAD

**Issue by 75py** [75py/habit-tracker#40]
```yaml
Description: |
    To provide more control over recurring habits, this feature introduces an 'End Time' field for habits with 'Hourly' or 'Interval' frequency types. This allows users to confine recurring tasks to a specific time window (e.g., 'Drink water every hour from 9:00 AM to 5:00 PM').
    
    As the application is pre-release, implementing a Room database migration is not required for this schema change.
Tasks:
    - |
    **1. Data Layer:**
        - Add a nullable `endTime: String` field to the `HabitEntity`.
        - Update the `AppDatabase` version. Since migration is not needed, ensure the schema is updated correctly (e.g., by using `fallbackToDestructiveMigration()`).
        - Update the DAO and `HabitRepositoryImpl` to handle saving and retrieving the new `endTime` field.
    - |
    **2. Domain Layer:**
        - Add the nullable `endTime` property to the `Habit` domain model.
        - Refactor the `GetTodayTasksUseCase` to generate task instances only within the `startTime` to `endTime` window. If `endTime` is null, the logic should work as it did before.
    - |
    **3. Presentation Layer (UI):**
        - In `HabitEditScreen`, add a UI element to select an End Time. This should be conditionally visible only for relevant frequency types (Hourly/Interval).
        - Use the `androidx.compose.material3.TimePicker` for the End Time selection, consistent with the Start Time picker.
        - Update the `HabitEditViewModel` to manage the state of the `endTime` field.
Testing:
    - "Update unit tests for `GetTodayTasksUseCase` to verify that tasks are correctly generated within the specified time window and not generated outside of it."
    - "Update or add UI tests for `HabitEditScreen` to include testing the new End Time picker."
Acceptance Criteria:
    - "A user can set both a start time and an end time for an interval-based habit."
    - "The application only generates task instances and sends notifications for that habit within the specified time window."
    - "Habits that do not have an end time set continue to function correctly."
```
