### ISSUE TITLE
[Bug] [Android] Notification Not Displayed; Action Executes Immediately

### ISSUE THREAD

**Issue by 75py** [75py/habit-tracker#43]
```yaml 
- issue_id: BUG-07
  title: "[Bug] [Android] Notification Not Displayed; Action Executes Immediately"
  body:
    Description: |
      On Android, the push notification is not being displayed at the scheduled time. Although `AlarmManager.setExactAndAllowWhileIdle()` is successfully scheduling a broadcast, it appears to be executing the `COMPLETE_ACTION` immediately in the background instead of first showing a notification.

      The correct flow should be:
      1. `AlarmManager` triggers a `BroadcastReceiver` at the scheduled time.
      2. The `BroadcastReceiver` builds and displays a system notification.
      3. The `COMPLETE_ACTION` is only executed when the user taps on the displayed notification.
    Tasks:
      - |
        **1. Refactor Broadcast Handling:**
          - Ensure there is a dedicated `BroadcastReceiver` whose purpose is solely to receive the alarm from `AlarmManager`.
          - Modify the `AlarmManager` setup to send its `PendingIntent` to this dedicated receiver.
      - |
        **2. Implement Notification Display:**
          - Inside the receiver's `onReceive` method, implement the logic to build and display a system notification using `NotificationManagerCompat`.
          - The notification's content (title, text) should be populated with the relevant habit information.
```
