### ISSUE TITLE
[Refactor] Implement Sequential Notification Scheduling

### ISSUE THREAD

**Issue by 75py** [75py/habit-tracker#45]
```yaml
- issue_id: REFACTOR-02
  title: "[Refactor] Implement Sequential Notification Scheduling"
  body:
    Description: |
      The current notification scheduling logic, handled by `ManageNotificationsUseCase.scheduleNotificationsForTodayTasks()`, has two significant problems:

      1.  **Schedules Past Notifications:** When triggered, it schedules all of today's notifications for a habit, including those for times that have already passed. For example, at 3:30 PM, it will still unnecessarily schedule notifications for 9:00 AM, 10:00 AM, etc.
      2.  **Reliant on App Launch:** Notifications for a new day are only scheduled when the UseCase is called from a ViewModel. If the date changes overnight, no new notifications will be scheduled until the user opens the app.
      
      To solve this, we will refactor the system to schedule notifications sequentially: only schedule the next upcoming notification, and when it fires, schedule the one after that.
    Tasks:
      - |
        **1. Refactor Domain Logic:**
          - Create a new UseCase, e.g., `ScheduleNextNotificationUseCase`, responsible for finding the single, next upcoming task for a given habit and scheduling it.
          - Deprecate or remove the old `scheduleNotificationsForTodayTasks()` UseCase.
      - |
        **2. Update the BroadcastReceiver:**
          - Modify the primary notification `BroadcastReceiver` on Android. When it is triggered by `AlarmManager`, it must now perform two actions in sequence:
            a) Build and display the notification for the current task.
            b) Immediately call the new `ScheduleNextNotificationUseCase` to schedule the *next* task in the sequence.
      - |
        **3. Update Initial Scheduling Triggers:**
          - Modify the logic for when a new habit is created or an existing one is edited. Instead of scheduling all tasks, it should now call `ScheduleNextNotificationUseCase` just once to start the scheduling chain.
      - |
        **4. Handle Device Restarts:**
          - Implement a mechanism (e.g., a `BOOT_COMPLETED` receiver on Android) to re-run the `ScheduleNextNotificationUseCase` for all active habits when the device restarts, ensuring the notification chain is not lost.
    Documentation:
      - "Update the `docs/ARCHITECTURE.md` file to describe the new sequential notification scheduling architecture (e.g., `Initial Schedule -> Alarm -> Receiver (Display & Re-schedule) -> ...`)."
    Acceptance Criteria:
      - "The app only schedules one future notification per habit at any given time."
      - "When a notification is displayed, the next notification in the sequence is automatically scheduled without user interaction."
      - "The notification chain continues to function correctly even after the day changes and after a device reboot."
```

Note: I mainly mentioned the Android implementation; please make sure that the iOS implementation is OK as well.
