### ISSUE TITLE
[CI] Setup Unit Test Automation with GitHub Actions

### ISSUE THREAD

**Issue by 75py** [75py/habit-tracker#5]
```yaml
Description: "Set up a CI (Continuous Integration) environment to automatically run unit tests on every push and pull request to the main branch."
Tasks:
  - "Create a `.github/workflows/` directory."
  - "Create a workflow file named `ci.yml`."
  - |
    Define the workflow with the following specifications:
      - Trigger: `on: [push, pull_request]`
      - Job Environment: `runs-on: ubuntu-latest`
      - Steps:
        1. Checkout the repository (`actions/checkout`)
        2. Set up Java (JDK) (`actions/setup-java`)
        3. Set up Gradle cache (`actions/cache`)
        4. Grant execute permission to the Gradle wrapper (`chmod +x ./gradlew`)
        5. Run unit tests for the shared module by executing `./gradlew testDebugUnitTest`.
Documentation:
  - "Add a CI badge to `README.md` to show the build status."
Acceptance Criteria:
  - "The GitHub Actions workflow is automatically triggered by pull requests and pushes."
  - "Unit tests are executed within the workflow, and the results (pass/fail) are visible on GitHub."
```
