### ISSUE TITLE
[Domain] Implement Domain Layer and UseCases

### ISSUE THREAD

**Issue by 75py** [75py/habit-tracker#7]
```yaml
Description: "Implement the domain layer, which is responsible for the app's business logic and serves as a crucial separation between the UI and data layers."
Tasks:
  - "Define the `HabitRepository.kt` interface in the `domain/repository` package."
  - "Define the `Habit.kt` domain model for UI display in the `domain/model` package (separate from the Entity)."
  - "Implement the following UseCases in the `domain/usecase` package: `GetAllHabitsUseCase`, `AddHabitUseCase`, `GetTodayTasksUseCase`, `CompleteTaskUseCase`."
Testing:
  - "Write unit tests for each UseCase's logic using a mocked `HabitRepository`."
Documentation:
  - |
    Update the "Domain Layer" section in `docs/ARCHITECTURE.md` to include:
      - The role of the Repository pattern
      - The specific responsibilities of each UseCase
      - A class diagram using Mermaid syntax to illustrate the relationship between UseCases and the Repository interface.
Acceptance Criteria:
  - "The Repository interface and UseCases are defined."
  - "Unit tests for the UseCases are passing in the CI workflow."
  - "Related documentation has been updated."
```
