### ISSUE TITLE
[UI] Implement Habit List and Edit Screens

### ISSUE THREAD

**Issue by 75py** [75py/habit-tracker#9]
```yaml
Description: "Implement the screens for displaying a list of habits and for adding/editing a habit using Compose Multiplatform."
Tasks:
  - "Implement the screen and ViewModel in the `presentation/habitlist` package: `HabitListScreen.kt` and `HabitListViewModel.kt`."
  - "Implement the screen and ViewModel in the `presentation/habitedit` package: `HabitEditScreen.kt` and `HabitEditViewModel.kt`."
  - "Inject the necessary UseCases into the ViewModels using Koin."
Testing:
  - "Write unit tests for the logic in `HabitListViewModel` and `HabitEditViewModel`."
  - "Create basic UI tests for list display and form input."
Documentation:
  - |
    Create a new `docs/SPECIFICATIONS.md` file and describe the specifications for the following screens:
      - Habit List Screen: Purpose, displayed items, user interactions.
      - Habit Add/Edit Screen: Purpose, form fields, validation rules.
  - |
    Update the "Presentation Layer" section in `docs/ARCHITECTURE.md` to describe the MVVM architecture and the role of ViewModels.
Acceptance Criteria:
  - "Users can add and view a list of habits."
  - "ViewModel unit tests are passing in the CI workflow."
  - "The screen specification document and related architecture documentation are created/updated."
```
